# Generated by Django 5.1.15 on 2026-08-07 19:07

import common.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0005_add_gateway_payment_methods'),
        ('foundation', '0009_seed_audit_logs_permission'),
        ('student', '0004_fix_updated_at_trigger_timing'),
    ]

    operations = [
        # See student/migrations/0001_initial.py and finance/migrations/0001_initial.py —
        # same implicit-schema-creation gap Phase 0 left open, for this app too.
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS payment_gateways;",
            reverse_sql="DROP SCHEMA IF EXISTS payment_gateways CASCADE;",
        ),
        migrations.CreateModel(
            name='GatewayTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=10)),
                ('merchant_trans_id', models.CharField(max_length=64)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=10)),
                ('provider_state', models.SmallIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('error_note', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.RESTRICT, related_name='gateway_transactions', to='finance.invoice')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('payment', models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_transactions', to='finance.payment')),
                ('student_profile', models.ForeignKey(db_column='student_profile_id', on_delete=django.db.models.deletion.RESTRICT, related_name='gateway_transactions', to='student.studentprofile')),
            ],
            options={
                'db_table': '"payment_gateways"."gateway_transactions"',
                'indexes': [models.Index(fields=['organization'], name='idx_gateway_txns_org'), models.Index(fields=['invoice'], name='idx_gateway_txns_invoice'), models.Index(fields=['provider', 'provider_transaction_id'], name='idx_gateway_txns_provider_txn')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_gateway_transactions_amount'), models.UniqueConstraint(fields=('organization', 'merchant_trans_id'), name='uq_gateway_transactions_merchant_trans_id'), models.UniqueConstraint(condition=models.Q(('provider_transaction_id__isnull', False)), fields=('provider', 'provider_transaction_id'), name='uq_gateway_transactions_provider_txn_id')],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=10)),
                ('merchant_id', models.CharField(max_length=100)),
                ('service_id', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_key', common.fields.EncryptedTextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
            ],
            options={
                'db_table': '"payment_gateways"."gateway_accounts"',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_gateway_accounts_org')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider'), name='uq_gateway_accounts_org_provider')],
            },
        ),
    ]
