# Generated by Django 5.1.15 on 2026-08-07 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0008_remove_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # See student/migrations/0001_initial.py — closing the same
        # implicit-schema-creation gap Phase 0 left open, for this app too.
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS notification;",
            reverse_sql="DROP SCHEMA IF EXISTS notification CASCADE;",
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=30)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('recipient', models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, db_column='sender_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"notification"."notifications"',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['recipient', 'read'], name='idx_notif_recipient_read'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_notif_org')],
            },
        ),
    ]
