# Generated by Django 5.1.15 on 2026-08-08 20:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # See student/migrations/0001_initial.py — every app's own initial
        # migration creates its own schema, closing the gap Phase 0 left
        # open (foundation/auth_custom's schemas had to be created by hand).
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS billing;",
            reverse_sql="DROP SCHEMA IF EXISTS billing CASCADE;",
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('max_branches', models.PositiveIntegerField(default=1)),
                ('max_students', models.PositiveIntegerField(default=50)),
                ('max_teachers', models.PositiveIntegerField(default=10)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': '"billing"."subscription_plans"',
                'ordering': ['display_order', 'price'],
                'indexes': [models.Index(fields=['is_active'], name='idx_subscription_plans_active')],
            },
        ),
    ]
