# Generated by Django 5.1.15 on 2026-08-08 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_subscriptionplan_price_and_more'),
        ('foundation', '0010_organization_subscription_plan_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('subscription_plan', models.ForeignKey(db_column='subscription_plan_id', on_delete=django.db.models.deletion.RESTRICT, related_name='platform_invoices', to='billing.subscriptionplan')),
            ],
            options={
                'db_table': '"billing"."platform_invoices"',
            },
        ),
        migrations.CreateModel(
            name='PlatformPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference_note', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('recorded_by', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('platform_invoice', models.ForeignKey(db_column='platform_invoice_id', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='billing.platforminvoice')),
            ],
            options={
                'db_table': '"billing"."platform_payments"',
            },
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_platform_invoices_org'),
        ),
        migrations.AddIndex(
            model_name='platforminvoice',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_platform_invoices_status'),
        ),
        migrations.AddConstraint(
            model_name='platforminvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='chk_platform_invoices_amount'),
        ),
        migrations.AddConstraint(
            model_name='platforminvoice',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='chk_platform_invoices_period'),
        ),
        migrations.AddIndex(
            model_name='platformpayment',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_platform_payments_org'),
        ),
        migrations.AddIndex(
            model_name='platformpayment',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['platform_invoice'], name='idx_platform_payments_invoice'),
        ),
        migrations.AddConstraint(
            model_name='platformpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_platform_payments_amount'),
        ),
    ]
