# Generated by Django 5.1.15 on 2026-08-07 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0008_remove_user_email'),
        ('groups', '0003_rls'),
    ]

    operations = [
        # See student/migrations/0001_initial.py — closing the same
        # implicit-schema-creation gap Phase 0 left open, for this app too.
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS schedule;",
            reverse_sql="DROP SCHEMA IF EXISTS schedule CASCADE;",
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='groups.group')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
            ],
            options={
                'db_table': '"schedule"."lessons"',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['group', 'date'], name='idx_lessons_group_date'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'date'], name='idx_lessons_org_date')],
                'constraints': [models.UniqueConstraint(fields=('group', 'date', 'start_time'), name='uq_lessons_group_date_start'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='chk_lessons_times')],
            },
        ),
    ]
