# Generated by Django 5.1.15 on 2026-08-06 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('foundation', '0008_remove_user_email'),
        ('student', '0004_fix_updated_at_trigger_timing'),
        ('teacher', '0004_fix_updated_at_trigger_timing'),
    ]

    operations = [
        # See student/migrations/0001_initial.py — closing the same
        # implicit-schema-creation gap Phase 0 left open, for this app too.
        # "group" is a reserved word — must stay quoted in the raw SQL.
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS "group";',
            reverse_sql='DROP SCHEMA IF EXISTS "group" CASCADE;',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='forming', max_length=20)),
                ('max_students', models.SmallIntegerField(default=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.branch')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='course.course')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('teacher', models.ForeignKey(db_column='teacher_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='teacher.teacherprofile')),
            ],
            options={
                'db_table': '"group"."groups"',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('transferred', 'Transferred'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('drop_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('student_profile', models.ForeignKey(db_column='student_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='student.studentprofile')),
            ],
            options={
                'db_table': '"group"."group_members"',
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_groups_org'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['course'], name='idx_groups_course'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['teacher'], name='idx_groups_teacher'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_groups_status'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_groups_org_code'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('max_students__gt', 0)), name='chk_groups_max_students'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='chk_groups_dates'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='chk_groups_times'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['group'], name='idx_group_members_group'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['student_profile'], name='idx_group_members_student'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_group_members_org_status'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'student_profile'), name='uq_group_members_student'),
        ),
    ]
