# Generated by Django 5.1.15 on 2026-08-06 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0008_remove_user_email'),
    ]

    operations = [
        # See student/migrations/0001_initial.py — closing the same
        # implicit-schema-creation gap Phase 0 left open, for this app too.
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS course;",
            reverse_sql="DROP SCHEMA IF EXISTS course CASCADE;",
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_weeks', models.SmallIntegerField(blank=True, null=True)),
                ('total_lessons', models.SmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('discontinued', 'Discontinued')], default='draft', max_length=20)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.branch')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
            ],
            options={
                'db_table': '"course"."courses"',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_courses_org'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_courses_status')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='uq_courses_org_code'), models.CheckConstraint(condition=models.Q(('duration_weeks__isnull', True), ('duration_weeks__gt', 0), _connector='OR'), name='chk_courses_duration_weeks'), models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='chk_courses_price')],
            },
        ),
    ]
