# Generated by Django 5.1.15 on 2026-08-07 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0008_remove_user_email'),
        ('groups', '0003_rls'),
        ('student', '0004_fix_updated_at_trigger_timing'),
    ]

    operations = [
        # See student/migrations/0001_initial.py — closing the same
        # implicit-schema-creation gap Phase 0 left open, for this app too.
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS homework;",
            reverse_sql="DROP SCHEMA IF EXISTS homework CASCADE;",
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('max_score', models.PositiveSmallIntegerField(default=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='groups.group')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
            ],
            options={
                'db_table': '"homework"."assignments"',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('graded_by', models.UUIDField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.assignment')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('student_profile', models.ForeignKey(db_column='student_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='student.studentprofile')),
            ],
            options={
                'db_table': '"homework"."submissions"',
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['group'], name='idx_assignments_group'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_assignments_org_status'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='chk_assignments_max_score'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['assignment'], name='idx_submissions_assignment'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['student_profile'], name='idx_submissions_student'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student_profile'), name='uq_submissions_assignment_student'),
        ),
    ]
