# Generated by Django 5.1.15 on 2026-07-31 20:44

import django.core.validators
import django.db.models.deletion
import foundation.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': '"foundation"."branches"',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('login_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('member_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('language', models.CharField(default='uz', max_length=10)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.branch')),
            ],
            options={
                'db_table': '"foundation"."users"',
            },
            managers=[
                ('objects', foundation.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='UZB', max_length=3)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=50)),
                ('locale', models.CharField(default='uz', max_length=10)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='free', max_length=50)),
                ('max_students', models.PositiveIntegerField(default=50)),
                ('max_teachers', models.PositiveIntegerField(default=10)),
                ('max_branches', models.PositiveIntegerField(default=1)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': '"foundation"."organizations"',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status'], name='idx_organizations_status'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['country'], name='idx_organizations_country')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_students__gt', 0)), name='chk_organizations_max_students'), models.CheckConstraint(condition=models.Q(('max_teachers__gt', 0)), name='chk_organizations_max_teachers')],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import')], max_length=20)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.organization')),
            ],
            options={
                'db_table': '"foundation"."audit_logs"',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('module', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"foundation"."permissions"',
                'indexes': [models.Index(fields=['module'], name='idx_permissions_module')],
                'constraints': [models.UniqueConstraint(fields=('module', 'action'), name='uq_permissions_module_action')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
            ],
            options={
                'db_table': '"foundation"."roles"',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='foundation.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='foundation.role')),
            ],
            options={
                'db_table': '"foundation"."role_permissions"',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('organization', 'Organization'), ('branch', 'Branch'), ('user', 'User')], default='organization', max_length=20)),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='foundation.branch')),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"foundation"."settings"',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='foundation.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"foundation"."user_roles"',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.CharField(choices=[('avatar', 'Avatar'), ('document', 'Document'), ('material', 'Material'), ('homework', 'Homework'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=20)),
                ('original_name', models.CharField(max_length=500)),
                ('stored_name', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('storage_path', models.TextField()),
                ('storage_provider', models.CharField(default='s3', max_length=50)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
            ],
            options={
                'db_table': '"foundation"."files"',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_files_org_id'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['entity_type', 'entity_id'], name='idx_files_entity'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['uploaded_by'], name='idx_files_uploaded_by'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'category'], name='idx_files_category')],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='chk_files_size')],
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_branches_org_id'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_branches_org_code'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='chk_branches_latitude'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='chk_branches_longitude'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-created_at'], name='idx_audit_logs_org_id'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='idx_audit_logs_user_id'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_audit_logs_entity'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='idx_audit_logs_action'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_users_org_id'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_users_org_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'last_name', 'first_name'], name='idx_users_name'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='chk_users_email_or_phone'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_roles_org_id'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uq_roles_org_slug'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='idx_role_permissions_role_id'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission'], name='idx_role_permissions_perm_id'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uq_role_permissions_role_perm'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['organization', 'key'], name='idx_settings_org_key'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['scope'], name='idx_settings_scope'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'user', 'key'), name='uq_settings_scope_key'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user'], name='idx_user_roles_user_id'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='idx_user_roles_role_id'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['organization'], name='idx_user_roles_org_id'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'organization'), name='uq_user_roles_user_role'),
        ),
    ]
