-- ============================================================================
-- EduCore LMS - Notifications Module
-- Schema: notification
-- Tables: notifications, notification_reads, announcements,
--         sms_logs, email_logs, push_notifications, telegram_notifications
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS notification;

-- ============================================================================
-- ENUM TYPES
-- ============================================================================

CREATE TYPE notification.notification_type_enum AS ENUM (
    'info', 'warning', 'success', 'error', 'reminder', 'system'
);

CREATE TYPE notification.notification_channel_enum AS ENUM (
    'in_app', 'sms', 'email', 'push', 'telegram'
);

CREATE TYPE notification.delivery_status_enum AS ENUM (
    'pending', 'sent', 'delivered', 'failed', 'bounced', 'rejected'
);

CREATE TYPE notification.announcement_status_enum AS ENUM (
    'draft', 'published', 'archived'
);

CREATE TYPE notification.audience_enum AS ENUM (
    'all', 'students', 'teachers', 'parents', 'staff', 'group', 'branch', 'custom'
);

-- ============================================================================
-- TABLE: notifications
-- Purpose: In-app notifications for users (payment due, homework, schedule changes).
-- Why: Real-time user engagement; event-driven communication within the platform.
-- Business Rules: Generated by system events. Can target individual or batch users.
-- Relationships: belongs to user (N:1), has many reads (1:N)
-- ============================================================================

CREATE TABLE notification.notifications (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id     UUID NOT NULL REFERENCES foundation.organizations(id) ON DELETE CASCADE,
    user_id             UUID NOT NULL REFERENCES foundation.users(id) ON DELETE CASCADE,
    notification_type   notification.notification_type_enum NOT NULL DEFAULT 'info',
    channel             notification.notification_channel_enum NOT NULL DEFAULT 'in_app',
    title               VARCHAR(255) NOT NULL,
    body                TEXT NOT NULL,
    action_url          TEXT,
    entity_type         VARCHAR(100),
    entity_id           UUID,
    is_read             BOOLEAN NOT NULL DEFAULT FALSE,
    read_at             TIMESTAMPTZ,
    metadata            JSONB DEFAULT '{}',
    expires_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_notifications_expiry CHECK (expires_at IS NULL OR expires_at > created_at)
);

CREATE INDEX idx_notifications_user_unread ON notification.notifications(user_id, is_read, created_at DESC)
    WHERE is_read = FALSE;
CREATE INDEX idx_notifications_user ON notification.notifications(user_id, created_at DESC);
CREATE INDEX idx_notifications_org ON notification.notifications(organization_id, created_at DESC);
CREATE INDEX idx_notifications_entity ON notification.notifications(entity_type, entity_id);
CREATE INDEX idx_notifications_expires ON notification.notifications(expires_at) WHERE expires_at IS NOT NULL AND is_read = FALSE;

-- Sample Record:
-- user_id: ..., title: 'Payment Reminder', body: 'Your invoice INV-2026-0001 is due in 3 days.',
-- notification_type: 'reminder', action_url: '/invoices/INV-2026-0001'

-- ============================================================================
-- TABLE: notification_reads
-- Purpose: Track read receipts for batch/broadcast notifications.
-- Why: Analytics on notification engagement; avoid re-sending.
-- Business Rules: One read record per user per notification.
-- Relationships: belongs to notification (N:1), belongs to user (N:1)
-- ============================================================================

CREATE TABLE notification.notification_reads (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    notification_id     UUID NOT NULL REFERENCES notification.notifications(id) ON DELETE CASCADE,
    user_id             UUID NOT NULL REFERENCES foundation.users(id) ON DELETE CASCADE,
    read_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    device_type         VARCHAR(50),

    CONSTRAINT uq_notification_reads UNIQUE (notification_id, user_id)
);

CREATE INDEX idx_notification_reads_notification ON notification.notification_reads(notification_id);
CREATE INDEX idx_notification_reads_user ON notification.notification_reads(user_id, read_at DESC);

-- ============================================================================
-- TABLE: announcements
-- Purpose: Organization-wide or targeted announcements (news, updates, events).
-- Why: Broadcast communication to groups of users; pinned/featured content.
-- Business Rules: Can target specific audiences. Has publish/archive lifecycle.
-- Relationships: belongs to organization (N:1), optionally to branch/group
-- ============================================================================

CREATE TABLE notification.announcements (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id     UUID NOT NULL REFERENCES foundation.organizations(id) ON DELETE CASCADE,
    branch_id           UUID REFERENCES foundation.branches(id) ON DELETE SET NULL,
    group_id            UUID REFERENCES "group".groups(id) ON DELETE SET NULL,
    author_id           UUID NOT NULL REFERENCES foundation.users(id) ON DELETE SET NULL,
    title               VARCHAR(255) NOT NULL,
    body                TEXT NOT NULL,
    audience            notification.audience_enum NOT NULL DEFAULT 'all',
    status              notification.announcement_status_enum NOT NULL DEFAULT 'draft',
    is_pinned           BOOLEAN NOT NULL DEFAULT FALSE,
    priority            SMALLINT NOT NULL DEFAULT 0,
    published_at        TIMESTAMPTZ,
    expires_at          TIMESTAMPTZ,
    attachment_urls     JSONB DEFAULT '[]',
    metadata            JSONB DEFAULT '{}',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMPTZ,
    created_by          UUID REFERENCES foundation.users(id),

    CONSTRAINT chk_announcements_priority CHECK (priority BETWEEN 0 AND 10)
);

CREATE INDEX idx_announcements_org ON notification.announcements(organization_id, status, published_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_announcements_audience ON notification.announcements(organization_id, audience) WHERE status = 'published' AND deleted_at IS NULL;
CREATE INDEX idx_announcements_branch ON notification.announcements(branch_id) WHERE branch_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX idx_announcements_pinned ON notification.announcements(organization_id, is_pinned) WHERE status = 'published' AND is_pinned = TRUE AND deleted_at IS NULL;

-- ============================================================================
-- TABLE: sms_logs
-- Purpose: Log of all SMS messages sent by the platform.
-- Why: Delivery tracking, cost analysis, compliance, debugging.
-- Business Rules: Immutable once created. Status updated by webhook/callback.
-- Relationships: belongs to organization (N:1), optionally to user
-- ============================================================================

CREATE TABLE notification.sms_logs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id     UUID NOT NULL REFERENCES foundation.organizations(id) ON DELETE CASCADE,
    user_id             UUID REFERENCES foundation.users(id) ON DELETE SET NULL,
    phone_number        VARCHAR(20) NOT NULL,
    message             TEXT NOT NULL,
    status              notification.delivery_status_enum NOT NULL DEFAULT 'pending',
    provider            VARCHAR(50) NOT NULL,
    provider_message_id VARCHAR(255),
    cost                DECIMAL(8, 4),
    currency            VARCHAR(3) DEFAULT 'UZS',
    sent_at             TIMESTAMPTZ,
    delivered_at        TIMESTAMPTZ,
    failed_reason       TEXT,
    metadata            JSONB DEFAULT '{}',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_sms_logs_org ON notification.sms_logs(organization_id, created_at DESC);
CREATE INDEX idx_sms_logs_user ON notification.sms_logs(user_id, created_at DESC) WHERE user_id IS NOT NULL;
CREATE INDEX idx_sms_logs_status ON notification.sms_logs(organization_id, status);
CREATE INDEX idx_sms_logs_provider_id ON notification.sms_logs(provider_message_id) WHERE provider_message_id IS NOT NULL;

-- ============================================================================
-- TABLE: email_logs
-- Purpose: Log of all emails sent by the platform.
-- Why: Delivery tracking, bounce handling, compliance, debugging.
-- Business Rules: Immutable once created. Status updated via webhook.
-- Relationships: belongs to organization (N:1), optionally to user
-- ============================================================================

CREATE TABLE notification.email_logs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id     UUID NOT NULL REFERENCES foundation.organizations(id) ON DELETE CASCADE,
    user_id             UUID REFERENCES foundation.users(id) ON DELETE SET NULL,
    to_email            VARCHAR(255) NOT NULL,
    from_email          VARCHAR(255) NOT NULL,
    subject             VARCHAR(500) NOT NULL,
    body_html           TEXT,
    body_text           TEXT,
    status              notification.delivery_status_enum NOT NULL DEFAULT 'pending',
    provider            VARCHAR(50) NOT NULL,
    provider_message_id VARCHAR(255),
    opened_at           TIMESTAMPTZ,
    clicked_at          TIMESTAMPTZ,
    bounced_at          TIMESTAMPTZ,
    bounce_reason       TEXT,
    metadata            JSONB DEFAULT '{}',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_email_logs_org ON notification.email_logs(organization_id, created_at DESC);
CREATE INDEX idx_email_logs_user ON notification.email_logs(user_id, created_at DESC) WHERE user_id IS NOT NULL;
CREATE INDEX idx_email_logs_status ON notification.email_logs(organization_id, status);
CREATE INDEX idx_email_logs_to ON notification.email_logs(to_email, created_at DESC);

-- ============================================================================
-- TABLE: push_notifications
-- Purpose: Log of mobile/web push notifications sent.
-- Why: Track delivery to devices; manage device tokens; analytics.
-- Relationships: belongs to user (N:1), belongs to organization (N:1)
-- ============================================================================

CREATE TABLE notification.push_notifications (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id     UUID NOT NULL REFERENCES foundation.organizations(id) ON DELETE CASCADE,
    user_id             UUID NOT NULL REFERENCES foundation.users(id) ON DELETE CASCADE,
    device_token        VARCHAR(500) NOT NULL,
    platform            VARCHAR(20) NOT NULL,
    title               VARCHAR(255) NOT NULL,
    body                TEXT NOT NULL,
    data_payload        JSONB DEFAULT '{}',
    status              notification.delivery_status_enum NOT NULL DEFAULT 'pending',
    provider            VARCHAR(50) NOT NULL DEFAULT 'fcm',
    provider_message_id VARCHAR(255),
    sent_at             TIMESTAMPTZ,
    delivered_at        TIMESTAMPTZ,
    opened_at           TIMESTAMPTZ,
    failed_reason       TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_push_platform CHECK (platform IN ('ios', 'android', 'web'))
);

CREATE INDEX idx_push_notifications_user ON notification.push_notifications(user_id, created_at DESC);
CREATE INDEX idx_push_notifications_org ON notification.push_notifications(organization_id, created_at DESC);
CREATE INDEX idx_push_notifications_status ON notification.push_notifications(organization_id, status);

-- ============================================================================
-- TABLE: telegram_notifications
-- Purpose: Log of Telegram bot messages sent to users.
-- Why: Telegram is a major communication channel in Central Asia; track delivery.
-- Relationships: belongs to user (N:1), belongs to organization (N:1)
-- ============================================================================

CREATE TABLE notification.telegram_notifications (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id     UUID NOT NULL REFERENCES foundation.organizations(id) ON DELETE CASCADE,
    user_id             UUID REFERENCES foundation.users(id) ON DELETE SET NULL,
    chat_id             VARCHAR(100) NOT NULL,
    message             TEXT NOT NULL,
    message_type        VARCHAR(20) NOT NULL DEFAULT 'text',
    status              notification.delivery_status_enum NOT NULL DEFAULT 'pending',
    telegram_message_id INTEGER,
    sent_at             TIMESTAMPTZ,
    delivered_at        TIMESTAMPTZ,
    failed_reason       TEXT,
    metadata            JSONB DEFAULT '{}',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_telegram_msg_type CHECK (message_type IN ('text', 'photo', 'document', 'video'))
);

CREATE INDEX idx_telegram_notifications_user ON notification.telegram_notifications(user_id, created_at DESC) WHERE user_id IS NOT NULL;
CREATE INDEX idx_telegram_notifications_org ON notification.telegram_notifications(organization_id, created_at DESC);
CREATE INDEX idx_telegram_notifications_chat ON notification.telegram_notifications(chat_id, created_at DESC);
CREATE INDEX idx_telegram_notifications_status ON notification.telegram_notifications(organization_id, status);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

CREATE TRIGGER trg_announcements_updated_at BEFORE UPDATE ON notification.announcements
    FOR EACH ROW EXECUTE FUNCTION foundation.update_updated_at();

CREATE TRIGGER trg_sms_logs_updated_at BEFORE UPDATE ON notification.sms_logs
    FOR EACH ROW EXECUTE FUNCTION foundation.update_updated_at();

CREATE TRIGGER trg_email_logs_updated_at BEFORE UPDATE ON notification.email_logs
    FOR EACH ROW EXECUTE FUNCTION foundation.update_updated_at();

CREATE TRIGGER trg_push_notifications_updated_at BEFORE UPDATE ON notification.push_notifications
    FOR EACH ROW EXECUTE FUNCTION foundation.update_updated_at();

CREATE TRIGGER trg_telegram_notifications_updated_at BEFORE UPDATE ON notification.telegram_notifications
    FOR EACH ROW EXECUTE FUNCTION foundation.update_updated_at();

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE notification.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification.notification_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification.sms_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification.email_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification.push_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification.telegram_notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON notification.notifications
    USING (organization_id = current_setting('app.current_org_id')::UUID);

CREATE POLICY tenant_isolation ON notification.announcements
    USING (organization_id = current_setting('app.current_org_id')::UUID);

CREATE POLICY tenant_isolation ON notification.sms_logs
    USING (organization_id = current_setting('app.current_org_id')::UUID);

CREATE POLICY tenant_isolation ON notification.email_logs
    USING (organization_id = current_setting('app.current_org_id')::UUID);

CREATE POLICY tenant_isolation ON notification.push_notifications
    USING (organization_id = current_setting('app.current_org_id')::UUID);

CREATE POLICY tenant_isolation ON notification.telegram_notifications
    USING (organization_id = current_setting('app.current_org_id')::UUID);
