# Generated by Django 5.1.15 on 2026-07-31 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0004_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=10)),
                ('token_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('attempts', models.SmallIntegerField(default=0)),
                ('max_attempts', models.SmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"auth"."email_verifications"',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_email_verifications_user'), models.Index(condition=models.Q(('status', 'pending')), fields=['email', 'code'], name='idx_email_verifications_code')],
                'constraints': [models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='chk_email_verif_attempts'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_email_verif_expiry')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.organization')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"auth"."login_attempts"',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_login_attempts_user'), models.Index(fields=['ip_address', '-created_at'], name='idx_login_attempts_ip'), models.Index(fields=['organization', '-created_at'], name='idx_login_attempts_org'), models.Index(fields=['login_id', '-created_at'], name='idx_login_attempts_login_id')],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"auth"."password_resets"',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_password_resets_user'), models.Index(condition=models.Q(('used_at__isnull', True)), fields=['token_hash'], name='idx_password_resets_token')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_password_resets_expiry')],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('attempts', models.SmallIntegerField(default=0)),
                ('max_attempts', models.SmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via', models.CharField(default='sms', max_length=20)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"auth"."phone_verifications"',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_phone_verifications_user'), models.Index(condition=models.Q(('status', 'pending')), fields=['phone', 'code'], name='idx_phone_verifications_code')],
                'constraints': [models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='chk_phone_verif_attempts'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_phone_verif_expiry')],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('device_info', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"auth"."refresh_tokens"',
                'indexes': [models.Index(fields=['user', 'status'], name='idx_refresh_tokens_user'), models.Index(condition=models.Q(('status', 'active')), fields=['token_hash'], name='idx_refresh_tokens_hash'), models.Index(condition=models.Q(('status', 'active')), fields=['expires_at'], name='idx_refresh_tokens_expires')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_refresh_tokens_expiry')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"auth"."sessions"',
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['user'], name='idx_sessions_user_active'), models.Index(condition=models.Q(('is_active', True)), fields=['organization'], name='idx_sessions_org'), models.Index(condition=models.Q(('is_active', True)), fields=['expires_at'], name='idx_sessions_expires'), models.Index(condition=models.Q(('is_active', True)), fields=['last_activity_at'], name='idx_sessions_last_activity')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_sessions_expiry')],
            },
        ),
    ]
