# Generated by Django 5.1.15 on 2026-08-07 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0008_remove_user_email'),
        ('groups', '0003_rls'),
        ('student', '0004_fix_updated_at_trigger_timing'),
    ]

    operations = [
        # See student/migrations/0001_initial.py — closing the same
        # implicit-schema-creation gap Phase 0 left open, for this app too.
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS finance;",
            reverse_sql="DROP SCHEMA IF EXISTS finance CASCADE;",
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('invoice_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='groups.group')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('student_profile', models.ForeignKey(db_column='student_profile_id', on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='student.studentprofile')),
            ],
            options={
                'db_table': '"finance"."invoices"',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online'), ('mobile_payment', 'Mobile Payment'), ('other', 'Other')], default='cash', max_length=20)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='finance.invoice')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('student_profile', models.ForeignKey(db_column='student_profile_id', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='student.studentprofile')),
            ],
            options={
                'db_table': '"finance"."payments"',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_invoices_org'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['student_profile'], name='idx_invoices_student'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_invoices_status'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'invoice_number'), name='uq_invoices_org_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='chk_invoices_total'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_payments_org'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['invoice'], name='idx_payments_invoice'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['student_profile'], name='idx_payments_student'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_payments_amount'),
        ),
    ]
