# Generated by Django 5.1.15 on 2026-08-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_seed_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online'), ('mobile_payment', 'Mobile Payment'), ('payme', 'Payme'), ('click', 'Click'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
