# Generated by Django 5.1.15 on 2026-08-06 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0008_remove_user_email'),
        ('groups', '0003_rls'),
        ('student', '0004_fix_updated_at_trigger_timing'),
    ]

    operations = [
        # See student/migrations/0001_initial.py — closing the same
        # implicit-schema-creation gap Phase 0 left open, for this app too.
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS attendance;",
            reverse_sql="DROP SCHEMA IF EXISTS attendance CASCADE;",
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('early_leave', 'Early Leave'), ('sick', 'Sick')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('marked_by', models.UUIDField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='groups.group')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('student_profile', models.ForeignKey(db_column='student_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student.studentprofile')),
            ],
            options={
                'db_table': '"attendance"."attendances"',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['group', 'date'], name='idx_attendance_group_date'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['student_profile'], name='idx_attendance_student'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_attendance_org_status')],
                'constraints': [models.UniqueConstraint(fields=('group', 'student_profile', 'date'), name='uq_attendance_group_student_date')],
            },
        ),
    ]
