# Generated by Django 5.1.15 on 2026-07-31 23:27

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0004_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Phase 0 (foundation/auth) relied on the schema already existing out
        # of band — a real gap (see backend Phase 1 plan). Every Phase 1 app
        # closes it by creating its own schema explicitly, right here.
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS student;",
            reverse_sql="DROP SCHEMA IF EXISTS student CASCADE;",
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('student_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('expelled', 'Expelled'), ('transferred', 'Transferred'), ('on_leave', 'On Leave'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('enrollment_date', models.DateField(default=datetime.date.today)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.branch')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"student"."student_profiles"',
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('other', 'Other')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('workplace', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('can_pickup', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(db_column='student_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='student.studentprofile')),
            ],
            options={
                'db_table': '"student"."student_parents"',
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('birth_certificate', 'Birth Certificate'), ('id_card', 'ID Card'), ('transcript', 'Transcript'), ('medical_record', 'Medical Record'), ('photo', 'Photo'), ('contract', 'Contract'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('file', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foundation.file')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(db_column='student_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student.studentprofile')),
            ],
            options={
                'db_table': '"student"."student_documents"',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(default=1)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('student_profile', models.ForeignKey(db_column='student_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='student.studentprofile')),
            ],
            options={
                'db_table': '"student"."emergency_contacts"',
            },
        ),
        migrations.CreateModel(
            name='StudentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('expelled', 'Expelled'), ('transferred', 'Transferred'), ('on_leave', 'On Leave'), ('pending', 'Pending')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('expelled', 'Expelled'), ('transferred', 'Transferred'), ('on_leave', 'On Leave'), ('pending', 'Pending')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('student_profile', models.ForeignKey(db_column='student_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='student.studentprofile')),
            ],
            options={
                'db_table': '"student"."student_status_history"',
            },
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_student_profiles_org'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_student_profiles_status'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['branch'], name='idx_student_profiles_branch'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'student_code'], name='idx_student_profiles_code'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'student_code'), name='uq_student_profiles_org_code'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('graduation_date__isnull', True), ('graduation_date__gte', models.F('enrollment_date')), _connector='OR'), name='chk_student_graduation'),
        ),
        migrations.AddIndex(
            model_name='studentparent',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['student_profile'], name='idx_student_parents_student'),
        ),
        migrations.AddIndex(
            model_name='studentparent',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_student_parents_org'),
        ),
        migrations.AddConstraint(
            model_name='studentparent',
            constraint=models.CheckConstraint(condition=models.Q(('phone__isnull', False), ('email__isnull', False), _connector='OR'), name='chk_parent_contact'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['student_profile'], name='idx_student_documents_student'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'document_type'], name='idx_student_documents_type'),
        ),
        migrations.AddConstraint(
            model_name='studentdocument',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('expiry_date__gt', models.F('issued_date')), _connector='OR'), name='chk_student_docs_expiry'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['student_profile'], name='idx_emergency_contacts_student'),
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 5)), name='chk_emergency_priority'),
        ),
        migrations.AddIndex(
            model_name='studentstatushistory',
            index=models.Index(fields=['student_profile', '-created_at'], name='idx_student_status_hist_stu'),
        ),
        migrations.AddIndex(
            model_name='studentstatushistory',
            index=models.Index(fields=['organization', '-created_at'], name='idx_student_status_hist_org'),
        ),
    ]
