# Generated by Django 5.1.15 on 2026-07-31 23:27

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0004_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # See student/migrations/0001_initial.py — closing the same
        # implicit-schema-creation gap Phase 0 left open, for this app too.
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS teacher;",
            reverse_sql="DROP SCHEMA IF EXISTS teacher CASCADE;",
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('teacher_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('hire_date', models.DateField(default=datetime.date.today)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience_years', models.SmallIntegerField(default=0)),
                ('education_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.branch')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"teacher"."teacher_profiles"',
            },
        ),
        migrations.CreateModel(
            name='TeacherDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('resume', 'Resume'), ('contract', 'Contract'), ('id_card', 'ID Card'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('file', models.ForeignKey(blank=True, db_column='file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foundation.file')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher_profile', models.ForeignKey(db_column='teacher_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teacher.teacherprofile')),
            ],
            options={
                'db_table': '"teacher"."teacher_documents"',
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('teacher_profile', models.ForeignKey(db_column='teacher_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='teacher.teacherprofile')),
            ],
            options={
                'db_table': '"teacher"."teacher_availability"',
            },
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('salary_type', models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly'), ('per_lesson', 'Per Lesson'), ('per_student', 'Per Student'), ('percentage', 'Percentage')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('teacher_profile', models.ForeignKey(db_column='teacher_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='teacher.teacherprofile')),
            ],
            options={
                'db_table': '"teacher"."teacher_salaries"',
            },
        ),
        migrations.CreateModel(
            name='TeacherSpecialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('proficiency_level', models.CharField(blank=True, max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('certificate_url', models.TextField(blank=True, null=True)),
                ('years_experience', models.SmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='foundation.organization')),
                ('teacher_profile', models.ForeignKey(db_column='teacher_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='teacher.teacherprofile')),
            ],
            options={
                'db_table': '"teacher"."teacher_specializations"',
            },
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_teacher_profiles_org'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'status'], name='idx_teacher_profiles_status'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['branch'], name='idx_teacher_profiles_branch'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'teacher_code'), name='uq_teacher_profiles_org_code'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.CheckConstraint(condition=models.Q(('termination_date__isnull', True), ('termination_date__gte', models.F('hire_date')), _connector='OR'), name='chk_teacher_termination'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.CheckConstraint(condition=models.Q(('experience_years__gte', 0), ('experience_years__lte', 60)), name='chk_teacher_experience'),
        ),
        migrations.AddIndex(
            model_name='teacherdocument',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['teacher_profile'], name='idx_teacher_documents_teacher'),
        ),
        migrations.AddIndex(
            model_name='teacherdocument',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'document_type'], name='idx_teacher_documents_type'),
        ),
        migrations.AddConstraint(
            model_name='teacherdocument',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('expiry_date__gt', models.F('issued_date')), _connector='OR'), name='chk_teacher_docs_expiry'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['teacher_profile', 'day_of_week'], name='idx_teacher_avail_teacher'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='idx_teacher_availability_org'),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='chk_availability_times'),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='chk_availability_dates'),
        ),
        migrations.AddIndex(
            model_name='teachersalary',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['teacher_profile'], name='idx_teacher_salaries_teacher'),
        ),
        migrations.AddIndex(
            model_name='teachersalary',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=['teacher_profile', 'is_active'], name='idx_teacher_salaries_active'),
        ),
        migrations.AddConstraint(
            model_name='teachersalary',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='chk_salary_amount'),
        ),
        migrations.AddConstraint(
            model_name='teachersalary',
            constraint=models.CheckConstraint(condition=models.Q(('percentage_value__isnull', True), models.Q(('percentage_value__gte', 0), ('percentage_value__lte', 100)), _connector='OR'), name='chk_salary_percentage'),
        ),
        migrations.AddConstraint(
            model_name='teachersalary',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='chk_salary_dates'),
        ),
        migrations.AddIndex(
            model_name='teacherspecialization',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['teacher_profile'], name='idx_teacher_spec_teacher'),
        ),
        migrations.AddIndex(
            model_name='teacherspecialization',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization', 'subject_name'], name='idx_teacher_spec_subject'),
        ),
        migrations.AddConstraint(
            model_name='teacherspecialization',
            constraint=models.UniqueConstraint(fields=('teacher_profile', 'subject_name'), name='uq_teacher_spec_subject'),
        ),
        migrations.AddConstraint(
            model_name='teacherspecialization',
            constraint=models.CheckConstraint(condition=models.Q(('years_experience__gte', 0)), name='chk_spec_experience'),
        ),
    ]
